#!/usr/bin/python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
# modified by Silvio Erdenberger <serdenberger@lenovo.com>
# 2018-01-20 Version BETA
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.

def inventory_lenovo_xcc_disk(info):
    for line in info:
        yield line[0], None

def check_lenovo_xcc_disk(item, _no_params, info):
    for line in info:
        if line[0] == item:
#            volt, crit, warn, crit_low, warn_low = map(lambda v: v, line[1:])
#            diskfruname, diskhealthstatus = map(str, line)
            diskfruname = line[0]
            diskhealthstatus = line[1]
#            print diskfruname,diskhealthstatus
            infotext = "%s Disk" % diskhealthstatus
            if diskhealthstatus == "Normal":
                state = 0
            elif diskhealthstatus == "Warning":
                state = 1
            else:
                state = 2
            return state, infotext

check_info["lenovo_xcc_disk"] = {
    'check_function'          : check_lenovo_xcc_disk,
    'inventory_function'      : inventory_lenovo_xcc_disk,
    'service_description'     : 'disk %s',
    'has_perfdata'            : True,
    'snmp_scan_function'      :
            lambda oid: oid('.1.3.6.1.2.1.1.1.0').lower().endswith(" armv7l"),
    'snmp_info'               : ('.1.3.6.1.4.1.19046.11.1.1.12.2.1', [ # diskTable.discEntry
                                        #1, # diskIndex
                                        2, # diskFruName
                                        3, # diskHealthStatus
                                ]),
}
